<template>
  <div class="column">
    <h1 class="text-h6 text-weight-900 no-letter-spacing q-mt-xl q-mb-lg">
      تولید متن تصادفی
    </h1>
    <q-card bordered class="no-shadow q-mb-xl">
      <q-card-section class="q-pa-xl">

        <q-item-label class="text-grey-7 q-mb-sm text-body1 no-letter-spacing">
          زبان
        </q-item-label>
        <q-select dropdown-icon="keyboard_arrow_down" dense outlined v-model="selectedLanguage" :options="languageOptions"
          color="primary" class="text-body1" popup-content-class="text-body1" />

        <div class="q-mt-lg">
          <q-item-label class="text-h6">
            تعداد پاراگراف: {{ paragraphCount }}
          </q-item-label>
          <q-slider v-model="paragraphCount" track-size="8px" thumb-color="primary" color="primary" :min="1" :max="20" />
        </div>

        <div class="q-mt-md q-mb-lg">
          <q-item-label class="q-mb-sm text-grey-7 text-body1 no-letter-spacing">
            نتیجه:
          </q-item-label>
          <q-input outlined readonly v-model="generatedText" type="textarea" class="text-body1"
            :class="direction"></q-input>
        </div>

        <div class="row q-gutter-x-sm">
          <q-btn unelevated class="text-body1" color="primary" @click="generateLoremIpsum">تولید متن تصادفی</q-btn>
          <q-btn outline class="text-body1" unelevated color="dark" @click="copyToClipboard"
            :disable="generatedText.length === 0">کپی
            متن</q-btn>
        </div>
      </q-card-section>


    </q-card>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import { Notify, useQuasar } from 'quasar';

const generatedText = ref('');
const paragraphCount = ref(1);
const selectedLanguage = ref('فارسی');
const languageOptions = ['فارسی', 'انگلیسی']

const loremIpsumEnglish = `I am Khashayar Shomali, a young engineer working in the field of web programming. This is a test text generated by me that has no value and is solely used for testing in software. This text can be useful for other lazy people like me to increase their work speed.`;

const loremIpsumPersian = `من خشایار شمالی هستم یک مهندس جوان که در حوزه برنامه نویسی وب فعالیت می‌کنم، این یک متن تستی تولید شده توسط من است که هیچ ارزشی ندارد و صرفا از آن برای تست در نرم‌افزار استفاده می‌کنم. این متن می‌تواند برای دیگر افراد تنبل همچون من هم مفید واقع شود تا سرعت کارشان را افزایش دهند.`

const generateLoremIpsum = () => {
  let loremText = '';
  if (selectedLanguage.value === 'انگلیسی') {
    for (let p = 0; p < paragraphCount.value; p++) {
      loremText += `${loremIpsumEnglish}\n\n`;
    }
  } else if (selectedLanguage.value === 'فارسی') {
    for (let p = 0; p < paragraphCount.value; p++) {
      loremText += `${loremIpsumPersian}\n\n`;
    }
  }
  generatedText.value = loremText.trim();
};

const copyToClipboard = () => {
  navigator.clipboard.writeText(generatedText.value)
    .then(() => {
      Notify.create({
        color: 'primary',
        message: 'متن با موفقیت کپی شد',
      });
    })
};

const direction = computed(() => {
  return selectedLanguage.value === 'انگلیسی' ? 'rtl' : 'ltr';
});

watch(selectedLanguage, () => {
  generatedText.value = '';
});

</script>

